### ISSUE TITLE
Around hooks is not finnished

### ISSUE THREAD

**Issue by mantaskujalis** [vinted/chained_job#22]
When returning `nil` https://github.com/vinted/chained_job/blob/master/lib/chained_job/start_chains.rb#L23 around callback is not being finished.
Return something to finish around callback

**Comment by laurynas** [comment]
Use `next` instead of `return` to finish around callback:
https://makandracards.com/makandra/46939-ruby-a-small-summary-of-what-return-break-and-next-means-for-blocks
